server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: "native"
  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config"
          search-locations: "file:///Users/bharath/onehome/config/"
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      liveness-state:
        enabled: true
      readiness-state:
        enabled: true
    endpoint:
      health:
        show-details: always
        probes:
          enabled: true